version: '3.8'
services:
  mongo:
    image: mongo
    container_name: taskmngr-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
