version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
    
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    environment:
      MONGODB_URI: mongodb://mongodb:27017/mern-app
      PORT: 5000
    depends_on:
      - mongodb
    networks:
      - app-network
    volumes:
      - ./server:/usr/src/app
      - server_node_modules:/usr/src/app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  server_node_modules: